spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cjjava/spring-cloud-simples.git
          searchPaths: cloud-config-repo
server:
  port: 8888
management:
  context_path: /admin
 