logging:
  file: logs/gateway.log

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

