---
spring:
  profiles: development
  jpa:
    show_sql: true
server:
  port: 8090
eureka:
  instance:
    nonSecurePort:  ${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
      
logging.level:
  org.springframework:
  cloud.netflix:
    feign: DEBUG
    
hystrix:
  command:
    default:
      execution:
        timeout.enabled: true
        isolation.thread.timeoutInMilliseconds: 60000
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000