server:
  port: 8989

spring:
  application:
    name: cloud-simple-turbine
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  instance:
    nonSecurePort: ${server.port:8989}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

turbine:
  aggregator:
    clusterConfig: CLOUD-SIMPLE-UI
  appConfig: cloud-simple-ui

logging:
  level: INFO